import type { Project } from '@/types';

export const DEFAULT_PROJECTS: Project[] = [
  {
    id: '1',
    title: 'E-Commerce Platform',
    description: 'A full-stack e-commerce application with real-time inventory management, payment processing, and admin dashboard.',
    techs: ['React', 'Node.js', 'MongoDB', 'Stripe'],
    url: 'https://github.com/ridzcoder/ecommerce',
    buttonText: 'View Project',
    imageUrl: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=600&h=375&fit=crop',
    sortOrder: 1,
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
  {
    id: '2',
    title: 'AI Chat Application',
    description: 'Intelligent chatbot powered by machine learning with natural language processing and context-aware responses.',
    techs: ['Python', 'FastAPI', 'React', 'TensorFlow'],
    url: 'https://github.com/ridzcoder/ai-chat',
    buttonText: 'View Demo',
    imageUrl: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=600&h=375&fit=crop',
    sortOrder: 2,
    createdAt: '2024-02-20',
    updatedAt: '2024-02-20',
  },
  {
    id: '3',
    title: 'Task Management System',
    description: 'Kanban-style project management tool with drag-and-drop, team collaboration, and real-time updates.',
    techs: ['Next.js', 'Supabase', 'TypeScript', 'Tailwind'],
    url: 'https://github.com/ridzcoder/taskflow',
    buttonText: 'Live Demo',
    imageUrl: 'https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=600&h=375&fit=crop',
    sortOrder: 3,
    createdAt: '2024-03-10',
    updatedAt: '2024-03-10',
  },
  {
    id: '4',
    title: 'Weather Dashboard',
    description: 'Real-time weather tracking app with interactive maps, 7-day forecasts, and severe weather alerts.',
    techs: ['React', 'TypeScript', 'Mapbox', 'OpenWeather'],
    url: 'https://github.com/ridzcoder/weather-app',
    buttonText: 'View Project',
    imageUrl: 'https://images.unsplash.com/photo-1504608524841-42fe6f032b4b?w=600&h=375&fit=crop',
    sortOrder: 4,
    createdAt: '2024-04-05',
    updatedAt: '2024-04-05',
  },
  {
    id: '5',
    title: 'Social Media Analytics',
    description: 'Dashboard for tracking social media metrics with data visualization, automated reports, and trend analysis.',
    techs: ['React', 'D3.js', 'Node.js', 'PostgreSQL'],
    url: 'https://github.com/ridzcoder/social-analytics',
    buttonText: 'Explore',
    imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&h=375&fit=crop',
    sortOrder: 5,
    createdAt: '2024-05-12',
    updatedAt: '2024-05-12',
  },
  {
    id: '6',
    title: 'Fitness Tracker App',
    description: 'Mobile-responsive fitness application with workout logging, progress charts, and personalized training plans.',
    techs: ['React Native', 'Firebase', 'TypeScript'],
    url: 'https://github.com/ridzcoder/fitness-tracker',
    buttonText: 'View Project',
    imageUrl: 'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=600&h=375&fit=crop',
    sortOrder: 6,
    createdAt: '2024-06-18',
    updatedAt: '2024-06-18',
  },
  {
    id: '7',
    title: 'Crypto Portfolio Tracker',
    description: 'Cryptocurrency portfolio manager with real-time price tracking, profit/loss calculations, and market alerts.',
    techs: ['Next.js', 'Prisma', 'CoinGecko API', 'Tailwind'],
    url: 'https://github.com/ridzcoder/crypto-tracker',
    buttonText: 'Live Demo',
    imageUrl: 'https://images.unsplash.com/photo-1621761191319-c6fb62004040?w=600&h=375&fit=crop',
    sortOrder: 7,
    createdAt: '2024-07-22',
    updatedAt: '2024-07-22',
  },
  {
    id: '8',
    title: 'Blog Platform',
    description: 'Markdown-powered blogging platform with syntax highlighting, SEO optimization, and content scheduling.',
    techs: ['Next.js', 'MDX', 'Supabase', 'Vercel'],
    url: 'https://github.com/ridzcoder/blog-platform',
    buttonText: 'Read More',
    imageUrl: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=600&h=375&fit=crop',
    sortOrder: 8,
    createdAt: '2024-08-30',
    updatedAt: '2024-08-30',
  },
];
